### ISSUE TITLE
Loading of checkpoints through yaml can fail for cyclic dependencies

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1981]
For the creation of checkpoints of `Process` instances in the engine, `yaml` is used to dump the object. The object can then be recreated in memory, in principle, through `yaml.load` of the dump. However, for certain instances of `WorkChain` this fails. This can be reproduced with this MWE:
```
import yaml
from aiida.common.extendeddicts import AttributeDict
from aiida.orm import construct_backend
backend = construct_backend()
computer = backend.computers.get(name='localhost')
d = AttributeDict()
d['computer'] = computer
bundle = yaml.dump(d)
loaded = yaml.load(bundle)
```
This will trigger an exception at the last line:
```
ConstructorError: found unconstructable recursive node
  in "<string>", line 4, column 15:
        _backend: &id001 !!python/object:aiida.orm ... 
```
The bundle that was generated by `yaml.dump` looks as follows:
```
!!python/object/new:aiida.common.extendeddicts.AttributeDict
dictitems:
  computer: !!python/object:aiida.orm.implementation.django.computer.DjangoComputer
    _backend: &id001 !!python/object:aiida.orm.implementation.django.backend.DjangoBackend
      _authinfos: !!python/object:aiida.orm.implementation.django.authinfo.DjangoAuthInfoCollection
        _backend: *id001
      _computers: !!python/object:aiida.orm.implementation.django.computer.DjangoComputerCollection
        _backend: *id001
      _logs: !!python/object:aiida.orm.implementation.django.log.DjangoLogCollection
        _backend: *id001
      _query_manager: !!python/object:aiida.backends.djsite.queries.DjangoQueryManager
        _backend: *id001
      _users: !!python/object:aiida.orm.implementation.django.user.DjangoUserCollection
        _backend: *id001
    _dbcomputer: !!python/object:aiida.orm.implementation.django.utils.ModelWrapper
      _model: !!python/object/apply:django.db.models.base.model_unpickle
        args:
        - !!python/tuple [db, DbComputer]
        - []
        - !!python/name:django.db.models.base.simple_class_factory ''
        state:
          _django_version: 1.8.19
          _state: !!python/object:django.db.models.base.ModelState {adding: false,
            db: default}
          description: !!python/unicode 'localhost'
          enabled: true
          hostname: !!python/unicode 'localhost'
          id: 1
          metadata: !!python/unicode '{"workdir": "/scratch/", "prepend_text": "",
            "mpirun_command": [], "shebang": "#!/bin/bash", "append_text": "", "default_mpiprocs_per_machine":
            1, "test": 1}'
          name: !!python/unicode 'localhost'
          scheduler_type: !!python/unicode 'direct'
          transport_params: !!python/unicode '{}'
          transport_type: !!python/unicode 'local'
          uuid: !!python/unicode '555f3245-4f75-4afb-a7a0-009aee5e8dc6'
```
The problem has to do with the cyclic dependency of the `Computer` instance on the `Backend` instance, which in turn has various collections, that each also have that very backend instance as a member. In principle this recursiveness is supported by `yaml`, partly made possible by the use of these `&id001` and `*id001` references.

Interestingly, even though the problem seems to originate in the reconstruction of the `Computer` object, the problem disappears if the wrapping `AttributeDict` is removed. The following, only slightly differing MWE, works just fine:
```
import yaml
from aiida.orm import construct_backend
backend = construct_backend()
computer = backend.computers.get(name='localhost')
bundle = yaml.dump(computer)
loaded = yaml.load(bundle)
```

After further investigation, it seems that it actually has to do with the `AttributeDict`, because replacing it with a normal dictionary in the first MWE, makes the problem disappear as well.

**Comment by greschd** [comment]
Here's a minimal reproducing YAML, which doesn't involve the Computer or backend:

```
test: !!python/object/new:aiida.common.extendeddicts.AttributeDict
  dictitems:
    a: &id001
      0: *id001
```

The corresponding YAML for a plain dict works:
```
test:
  a: &id001
    0: *id001
```
